from typing import Any
from fastapi import APIRouter
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel

router = APIRouter(prefix="/api/export", tags=["Export Reports"])

class ReportExportRequest(BaseModel):
    title: str = "AI Data Analysis Executive Report"
    tables: list[str] = []
    messages: list[dict[str, Any]] = []

@router.post("/markdown", response_class=PlainTextResponse)
async def export_markdown_report(payload: ReportExportRequest):
    """Generates an executive markdown report summarizing the analysis session."""
    md_lines = [
        f"# {payload.title}",
        f"*Generated by InsightPulse AI Data Analyst*",
        f"\n---\n",
        "## Analyzed Datasets",
    ]

    for t in payload.tables:
        md_lines.append(f"- `{t}`")

    md_lines.append("\n## Key Questions & Analytical Findings\n")

    for idx, msg in enumerate(payload.messages):
        role = msg.get("role", "user")
        content = msg.get("content", "")
        reasoning = msg.get("reasoning", "")
        sql = msg.get("sql_query", "")

        if role == "user":
            md_lines.append(f"### Q{idx//2 + 1}: {content}\n")
        else:
            if reasoning:
                md_lines.append(f"**Analytical Reasoning:**\n> {reasoning}\n")
            if sql:
                md_lines.append(f"**DuckDB SQL Query:**\n```sql\n{sql}\n```\n")
            md_lines.append(f"**Findings & Business Insight:**\n{content}\n")
            md_lines.append("---\n")

    return "\n".join(md_lines)
